[package]
name = "wiremock_logical_matchers"
version = "0.1.0"
authors = [ "Charles Lechasseur <shiftingbeard@gmx.com>" ]
edition = "2018"

readme = "README.md"
license = "MIT"

repository = "https://github.com/clechasseur/wiremock_logical_matchers"
documentation = "https://docs.rs/wiremock_logical_matchers/"

description = "Logical matchers for use with wiremock."

keywords = [ "test", "http", "mocking", "mock", "wiremock" ]
categories = [ "development-tools", "asynchronous" ]

[dependencies]
wiremock = "0"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
reqwest = "0.11.18"
