name: Build / tests

on: [ push ]

jobs:
  rust-build:
    name: Rust build for Rust ${{ matrix.toolchain }} on ${{ matrix.os }}${{ matrix.experimental && ' (experimental)' || '' }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ 1.68.2, stable, beta, nightly ]
        os: [ ubuntu, macos, windows ]
        include:
          - experimental: false
          - toolchain: beta
            experimental: true
          - toolchain: nightly
            experimental: true
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain ${{ matrix.toolchain }} with clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: Output Rust toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets --all-features

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release
